version: "3.7"
name: kfw-mastr

services:
  postgis-database:
      image: postgis/postgis:15-3.3
      container_name: postgis-database
      ports:
        - '5512:5432' #host:container
      environment:
        POSTGRES_DB: kfw-mastr
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      volumes:
        - kfwmastrDatabaseVolume:/var/lib/postgresql/data

volumes:
  kfwmastrDatabaseVolume: